// src/views/ProfileView.vue
<template>
  <div class="flex flex-col h-full bg-slate-900 relative">
    <div class="p-6 bg-slate-800 pb-10 rounded-b-[2rem] shadow-lg mb-4">
      <div class="flex justify-between items-start">
        <button @click="$router.push('/dashboard')">
          <ArrowLeft class="text-white" />
        </button>
        <LanguageSwitcher v-model:currentLang="lang" @update:currentLang="setLang" />
      </div>
      
      <!-- Avatar Section -->
      <div class="flex flex-col items-center mt-[-20px]">
        <div class="relative group cursor-pointer" @click="handleAvatarClick">
          <div class="w-24 h-24 rounded-full border-4 border-slate-900 p-1 bg-gradient-to-tr from-emerald-500 to-slate-700 shadow-xl overflow-hidden relative">
            <img 
              v-if="store.userInfo.avatar"
              :src="store.userInfo.avatar" 
              alt="avatar" 
              class="w-full h-full rounded-full object-cover bg-slate-900" 
            />
            <img 
              v-else
              src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" 
              alt="avatar" 
              class="rounded-full bg-slate-900 w-full h-full" 
            />
            <!-- Overlay Hint -->
            <div class="absolute inset-0 bg-black/50 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
              <Camera class="text-white" :size="24" />
            </div>
          </div>
          <input type="file" ref="fileInputRef" @change="handleFileChange" hidden accept="image/*" />
        </div>

        <!-- Nickname Section -->
        <div class="mt-3 flex items-center justify-center gap-2 h-8">
          <div v-if="isEditingName" class="flex items-center bg-slate-900 rounded-full px-2 border border-emerald-500 animate-in fade-in duration-200">
            <input 
              v-model="tempName" 
              type="text"
              class="bg-transparent text-white text-sm font-bold w-32 outline-none text-center"
              @keyup.enter="handleNameSave"
            />
            <button @click="handleNameSave" class="p-1 text-emerald-400 hover:text-white">
              <Check :size="16"/>
            </button>
            <button @click="isEditingName = false" class="p-1 text-rose-400 hover:text-white">
              <X :size="16"/>
            </button>
          </div>
          <template v-else>
            <h2 class="text-xl font-bold text-white">{{ store.userInfo.nickname }}</h2>
            <button @click="isEditingName = true" class="text-slate-500 hover:text-emerald-400 transition-colors">
              <Edit3 :size="16" />
            </button>
          </template>
        </div>
        <p class="text-slate-400 text-xs mt-1">UID: 88392010</p>
      </div>

      <div class="flex justify-around mt-6">
        <div class="text-center">
          <div class="text-lg font-mono font-bold text-white">128</div>
          <div class="text-[10px] text-slate-500 uppercase">{{ t.profile.totalOrders }}</div>
        </div>
        <div class="text-center">
          <div class="text-lg font-mono font-bold text-emerald-400">99%</div>
          <div class="text-[10px] text-slate-500 uppercase">{{ t.profile.rate }}</div>
        </div>
        <div class="text-center">
          <div class="text-lg font-mono font-bold text-white">Level 3</div>
          <div class="text-[10px] text-slate-500 uppercase">{{ t.profile.level }}</div>
        </div>
      </div>
    </div>

    <div class="flex-1 overflow-y-auto no-scrollbar">
      <div class="mx-4 bg-slate-900 rounded-xl overflow-hidden mb-4">
        <p class="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">{{ t.profile.groupTrans }}</p>
        <MenuItem :icon="FileText" :label="t.profile.record" @click="$router.push('/transaction-history')" />
        <MenuItem :icon="CreditCard" :label="t.profile.account" @click="$router.push('/payment-account')" />
      </div>
      
      <!-- NEW GROUP: Referral & Membership -->
      <div class="mx-4 bg-slate-900 rounded-xl overflow-hidden mb-4">
        <p class="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Member Center</p>
        <MenuItem :icon="Users" :label="t.profile.referral" @click="$router.push('/referral-center')" />
        <MenuItem :icon="Crown" :label="t.profile.membership" @click="$router.push('/membership')" />
      </div>

      <div class="mx-4 bg-slate-900 rounded-xl overflow-hidden">
        <p class="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">{{ t.profile.groupSys }}</p>
        <MenuItem :icon="Shield" :label="t.profile.security" @click="$router.push('/security-center')" />
        <MenuItem :icon="User" :label="t.profile.service" @click="$router.push('/customer-service')" />
        <div class="p-4 mt-4">
          <NeonButton variant="outline" fullWidth @click="$router.push('/login')">
            <LogOut :size="16" class="mr-2" />{{ t.profile.logout }}
          </NeonButton>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ArrowLeft, Camera, Check, X, Edit3, FileText, CreditCard, Users, Crown, Shield, User, LogOut } from 'lucide-vue-next'
import NeonButton from '@/components/NeonButton.vue'
import LanguageSwitcher from '@/components/LanguageSwitcher.vue'
import MenuItem from '@/components/MenuItem.vue'
import { useTranslation } from '@/composables/useTranslation'
import { useAppStore } from '@/stores/app'

const { t, lang, setLang } = useTranslation()
const store = useAppStore()

const isEditingName = ref(false)
const tempName = ref(store.userInfo.nickname)
const fileInputRef = ref(null)

function handleNameSave() {
  store.updateUserInfo({ nickname: tempName.value })
  isEditingName.value = false
}

function handleAvatarClick() {
  fileInputRef.value.click()
}

function handleFileChange(e) {
  const file = e.target.files[0]
  if (file) {
    const reader = new FileReader()
    reader.onloadend = () => {
      store.updateUserInfo({ avatar: reader.result })
    }
    reader.readAsDataURL(file)
  }
}
</script>

// src/views/ProfileView.tsx
import React, { useState, useRef } from 'react';
import { 
  ArrowLeft, ChevronRight, FileText, CreditCard, Shield, 
  User, LogOut, Users, Crown, Camera, Edit3, Check, X, 
  ZoomIn, Move, Save
} from 'lucide-react';
import { ViewProps } from '../types';
import { NeonButton, LanguageSwitcher } from '../components';

const ProfileView: React.FC<ViewProps> = ({ navigate, t, lang, setLang, userInfo, setUserInfo }) => {
  const [isEditingName, setIsEditingName] = useState(false);
  const [tempName, setTempName] = useState(userInfo?.nickname || 'Player_99');
  const [showAvatarModal, setShowAvatarModal] = useState(false);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  interface MenuItemProps {
    icon: React.ElementType;
    label: string;
    onClick: () => void;
    sub?: string;
  }

  const MenuItem: React.FC<MenuItemProps> = ({ icon: Icon, label, onClick, sub }) => (
    <div onClick={onClick} className="flex items-center justify-between p-4 border-b border-slate-800 hover:bg-slate-800 transition-colors cursor-pointer">
      <div className="flex items-center">
        <div className="p-2 bg-slate-800 rounded-lg mr-3 text-emerald-500">
          <Icon size={20} />
        </div>
        <div>
          <div className="text-white text-sm font-bold">{label}</div>
          {sub && <div className="text-[10px] text-slate-500">{sub}</div>}
        </div>
      </div>
      <ChevronRight size={16} className="text-slate-600" />
    </div>
  );

  const handleNameSave = () => {
    setUserInfo(prev => ({ ...prev, nickname: tempName }));
    setIsEditingName(false);
  };

  const handleAvatarClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setSelectedImage(reader.result as string);
        setShowAvatarModal(true);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAvatarConfirm = () => {
    setUserInfo(prev => ({ ...prev, avatar: selectedImage }));
    setShowAvatarModal(false);
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 relative">
      <div className="p-6 bg-slate-800 pb-10 rounded-b-[2rem] shadow-lg mb-4">
        <div className="flex justify-between items-start">
          <button onClick={() => navigate('dashboard')}>
            <ArrowLeft className="text-white" />
          </button>
          <LanguageSwitcher currentLang={lang} setLang={setLang} />
        </div>
        
        {/* Avatar Section */}
        <div className="flex flex-col items-center mt-[-20px]">
          <div className="relative group cursor-pointer" onClick={handleAvatarClick}>
            <div className="w-24 h-24 rounded-full border-4 border-slate-900 p-1 bg-gradient-to-tr from-emerald-500 to-slate-700 shadow-xl overflow-hidden relative">
              {userInfo?.avatar ? (
                <img src={userInfo.avatar} alt="avatar" className="w-full h-full rounded-full object-cover bg-slate-900" />
              ) : (
                <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" alt="avatar" className="rounded-full bg-slate-900 w-full h-full" />
              )}
              <div className="absolute inset-0 bg-black/50 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                <Camera className="text-white" size={24} />
              </div>
            </div>
            <input type="file" ref={fileInputRef} onChange={handleFileChange} hidden accept="image/*" />
          </div>

          {/* Nickname Section */}
          <div className="mt-3 flex items-center justify-center gap-2 h-8">
            {isEditingName ? (
              <div className="flex items-center bg-slate-900 rounded-full px-2 border border-emerald-500 animate-in fade-in zoom-in duration-200">
                <input 
                  type="text" 
                  value={tempName} 
                  onChange={(e) => setTempName(e.target.value)}
                  className="bg-transparent text-white text-sm font-bold w-32 outline-none text-center"
                  autoFocus
                />
                <button onClick={handleNameSave} className="p-1 text-emerald-400 hover:text-white">
                  <Check size={16}/>
                </button>
                <button onClick={() => setIsEditingName(false)} className="p-1 text-rose-400 hover:text-white">
                  <X size={16}/>
                </button>
              </div>
            ) : (
              <>
                <h2 className="text-xl font-bold text-white">{userInfo?.nickname || 'Player_99'}</h2>
                <button onClick={() => setIsEditingName(true)} className="text-slate-500 hover:text-emerald-400 transition-colors">
                  <Edit3 size={16} />
                </button>
              </>
            )}
          </div>
          <p className="text-slate-400 text-xs mt-1">UID: 88392010</p>
        </div>

        <div className="flex justify-around mt-6">
          <div className="text-center">
            <div className="text-lg font-mono font-bold text-white">128</div>
            <div className="text-[10px] text-slate-500 uppercase">{t.profile.totalOrders}</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-mono font-bold text-emerald-400">99%</div>
            <div className="text-[10px] text-slate-500 uppercase">{t.profile.rate}</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-mono font-bold text-white">Level 3</div>
            <div className="text-[10px] text-slate-500 uppercase">{t.profile.level}</div>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto no-scrollbar">
        <div className="mx-4 bg-slate-900 rounded-xl overflow-hidden mb-4">
          <p className="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">{t.profile.groupTrans}</p>
          <MenuItem icon={FileText} label={t.profile.record} onClick={() => navigate('transaction-history')} />
          <MenuItem icon={CreditCard} label={t.profile.account} onClick={() => navigate('payment-account')} />
        </div>
        
        <div className="mx-4 bg-slate-900 rounded-xl overflow-hidden mb-4">
          <p className="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Member Center</p>
          <MenuItem icon={Users} label={t.profile.referral} onClick={() => navigate('referral-center')} />
          <MenuItem icon={Crown} label={t.profile.membership} onClick={() => navigate('membership')} />
        </div>

        <div className="mx-4 bg-slate-900 rounded-xl overflow-hidden">
          <p className="px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">{t.profile.groupSys}</p>
          <MenuItem icon={Shield} label={t.profile.security} onClick={() => navigate('security-center')} />
          <MenuItem icon={User} label={t.profile.service} onClick={() => navigate('customer-service')} />
          <div className="p-4 mt-4">
            <NeonButton variant="outline" fullWidth onClick={() => navigate('login')}>
              <LogOut size={16} className="mr-2" />
              {t.profile.logout}
            </NeonButton>
          </div>
        </div>
      </div>

      {/* Avatar Crop Modal */}
      {showAvatarModal && (
        <div className="absolute inset-0 bg-black/90 z-50 flex flex-col items-center justify-center p-6 animate-in fade-in zoom-in duration-200">
          <div className="w-full max-w-xs bg-slate-800 rounded-2xl overflow-hidden shadow-2xl border border-slate-700">
            <div className="p-4 border-b border-slate-700 flex justify-between items-center">
              <span className="text-white font-bold">{t.profile.cropTitle}</span>
              <button onClick={() => setShowAvatarModal(false)}>
                <X className="text-slate-400 hover:text-white" />
              </button>
            </div>
            <div className="h-64 bg-black relative overflow-hidden flex items-center justify-center">
              {selectedImage && (
                <img src={selectedImage} alt="crop preview" className="max-w-none w-full opacity-80" />
              )}
              <div className="absolute inset-0 border-[100px] border-black/60 rounded-full pointer-events-none"></div>
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="w-48 h-48 rounded-full border-2 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.3)]"></div>
              </div>
              <div className="absolute bottom-2 right-2 bg-black/50 px-2 py-1 rounded text-[10px] text-white flex items-center">
                <Move size={12} className="mr-1" /> Drag to move
              </div>
            </div>
            <div className="p-4 space-y-4">
              <div className="flex items-center gap-3">
                <ZoomIn size={16} className="text-slate-400" />
                <input type="range" min="1" max="3" step="0.1" defaultValue="1" className="w-full h-1 bg-slate-600 rounded-lg appearance-none cursor-pointer accent-emerald-500" />
              </div>
              <NeonButton fullWidth onClick={handleAvatarConfirm}>
                <Save size={16} className="mr-2" /> {t.common.confirm}
              </NeonButton>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProfileView;
